import { Permissions } from "miauth-js";

export const AllScope = [
  Permissions.AccountRead,
  Permissions.AccountWrite,
  Permissions.NotesRead,
  Permissions.NotesWrite,
  Permissions.BlocksRead,
  Permissions.BlocksWrite,
  Permissions.DriveRead,
  Permissions.DriveWrite,
  Permissions.FavoritesRead,
  Permissions.FavoritesWrite,
  Permissions.FollowingRead,
  Permissions.FollowingWrite,
  Permissions.MessagingRead,
  Permissions.messagingWrite,
  Permissions.MutesRead,
  Permissions.MutesWrite,
  Permissions.NotificationsRead,
  Permissions.NotificationsWrite,
  Permissions.ReactionsRead,
  Permissions.ReactionsWrite,
  Permissions.VotesWrite,
  Permissions.VotesRead,
  Permissions.PagesWrite,
  Permissions.PagesRead,
  Permissions.PagelikesWrite,
  Permissions.PagelikesRead,
  Permissions.UsergroupsWrite,
  Permissions.ChannelsRead,
  Permissions.ChannelsWrite,
];
